#!/usr/bin/env bash

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source "$script_dir/bash-helpers"

dry="0"

while [[ $# -gt 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {

    if [[ $dry -eq 1 ]]; then
        echo "[DRY RUN]: $*"
    else
        echo "$*"
    fi

}


execute() {
    log "Executing: $*"

    if [[ $dry -eq 1 ]]; then
        return
    fi
    "$@"
}

log "--------- dev-env ---------"


cd "$script_dir" || exit

copy_dir ./bin/.config ~/.config
copy_file ./bin/antigen.zsh ~/
copy_file ./bin/.zshrc ~/
copy_file ./bin/.tmux.conf ~/
