#!/usr/bin/env bash

script_dir=$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)
source "$script_dir/bash-helpers"

dry="0"

while [[ $# -gt 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {

    if [[ $dry -eq 1 ]]; then
        echo "[DRY RUN]: $*"
    else
        echo "$*"
    fi

}


execute() {
    log "Executing: $*"

    if [[ $dry -eq 1 ]]; then
        return
    fi
    "$@"
}

copy_file() {
    from=$1
    to=$2
    name=$(basename "$from")
    execute rm "$to"/"$name"
    execute cp "$from" "$to"/"$name"
}

copy_dir() {
    pushd "$1" > /dev/null || exit
    to=$2
    dirs=$(find . -maxdepth 1 -mindepth 1 -type d)
    execute mkdir -p "$to"

    for dir in $dirs; do
        execute rm -rf "$to"/"$dir"
        execute cp -r "$dir" "$to"/"$dir"
    done
    popd > /dev/null || exit
}

log "--------- dev-env ---------"


cd "$script_dir" || exit

copy_dir ./bin/.config ~/.config
copy_dir ./bin/.local ~/.local
copy_file ./bin/antigen.zsh ~/
copy_file ./bin/.zshrc ~/
copy_file ./bin/.tmux.conf ~/
copy_file ./bin/.globalgitignore ~/
