#!/usr/bin/env bash

script_dir=$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)
filter=""
dry="0"


while [[ $# -gt 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    else
        filter="$1"
    fi
    shift
done

log() {

    if [[ $dry -eq 1 ]]; then
        echo "[DRY RUN]: $*"
    else
        echo "$*"
    fi

}


execute() {
    log "Executing: $*"

    if [[ $dry -eq 1 ]]; then
        return
    fi
    "$@"
}


echo "$script_dir - $filter"

cd "$script_dir" || exit

scripts=$(find ./runs -maxdepth 1 -mindepth 1  -type f)

for script in $scripts; do
    if echo "$script" | grep -qv "$filter"; then
        log "filtered: $script"
        continue
    fi

    execute ./"$script"
done
