#!/usr/bin/env bash

script_dir=$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/.." && pwd)
source "$script_dir/bash-helpers"

echo "Setting up Core packages..."

general_to_install=(
    git
    curl
    cmake
    make
    ripgrep
    tmux
    unzip
)

ubuntu_to_install=(
    build-essential
    libssl-dev
    python3-pip
    libc6
    golang-go
    python3.12-venv
)

macos_to_install=(
    wget
    python3
    go
)

# Run the unified installer
install_package general_to_install ubuntu_to_install macos_to_install

echo "Setting up Python virtual environment..."
python3 -m venv ~/.venv --clear
echo "Python virtual environment set up"

echo "Installing fzf..."
go install github.com/junegunn/fzf@latest
echo "fzf installed"

echo "Installing deno..."
curl -fsSL https://deno.land/install.sh | sh
echo "deno installed"

echo "Installing Cargo..."
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
echo "Cargo installed"
