#!/usr/bin/env bash

script_dir=$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/.." && pwd)
source "$script_dir/bash-helpers"

echo "Setting up Core packages..."

general_to_install=(
    git
    curl
    cmake
    make
    fzf
    ripgrep
    tmux
)

ubuntu_to_install=(
    build-essential
    libssl-dev
    python3-pip
    libc6
    golang-go
)

macos_to_install=(
    wget
    python3
    go
)

# Run the unified installer
install_package general_to_install ubuntu_to_install macos_to_install
