#!/usr/bin/env bash

script_dir=$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/.." && pwd)
source "$script_dir/bash-helpers"

echo "Setting up Zsh ..."

general_to_install=(
    git
    curl
    zsh
)

echo "Installing general packages ..."
install_package general_to_install
echo "General packages installed."

echo "Installing Oh My Zsh ..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
echo "Oh My Zsh installed."
